######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 14 01:33:10 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += en_keymap.h keyboard.h
FORMS += keyboard.ui
SOURCES += keyboard.cpp main.cpp
